# Generated by Django 4.0.5 on 2022-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_description1_projectgallery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgallery',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='construction_phase',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='country',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='design_phase',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='year',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
