# Generated by Django 4.0.5 on 2022-06-09 13:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectgallery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_detail_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='media/Projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
