# Generated by Django 4.0.5 on 2022-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_project_detail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(),
        ),
    ]
