# Generated by Django 4.0.5 on 2022-06-09 14:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
